tested_code_path : ./tests/test_input
output_path : ./tests/test_output
test_case_path : ./tests/testcase
temp_files_path : ./tests/temp_files
students_list:
- PCS 9 - Wrong Answer
- PCS 9 - Right Answer
- PCS 9 - Mr.Timeout
- PCS 9 - Ms.Memout
- PCS 9 - Dangerous Behavior
- PCS 9 - No Homework
problems_list: 
- addition.py
- ./folder/subtraction.py
- card_functions.py